refactored to use Robinhood's API; improved output with span parameters

diff --git a/panel_ticker b/panel_ticker
--- a/panel_ticker
+++ b/panel_ticker
@@ -3,15 +3,26 @@
 # https://github.com/tablespoon/panel_ticker
 
 SYMBOL=$1
-SLEEP_TIME=180 # minimum number of seconds between queries; should be long enough to avoid being blocked
+SLEEP_TIME=10 # minimum number of seconds between queries
 START_TIME=4:00
 OPENING_BELL_TIME=9:30
 CLOSING_BELL_TIME=16:00
 END_TIME=20:00
 OUTPUT_FILE="/tmp/$(basename $0)-${SYMBOL}"
 
-USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0"
+USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
 DELIM="#"
+
+
+error() {
+	echo "$0 Error: $@" 1>&2
+	exit 1
+}
+
+
+query() {
+	curl -s --compressed -A "$USER_AGENT" -L "$1"
+}
 
 
 convertToSeconds() {
@@ -39,9 +50,20 @@ convertFromSeconds() {
 }
 
 
+okayToQuery() {
+	local output_file_age=$(( current_second - $(date -r "$OUTPUT_FILE" +%s) ))
+	if ( tradingActive || [[ $logged_phase != "0" ]] ) && [[ $output_file_age -gt $SLEEP_TIME ]]; then
+		return 0
+	fi
+	return 1
+}
+
 
 tradingActive() {
 	if [[ $day == [1-5] ]]; then
+#		if [[ "$all_day_tradability" == "tradable" ]]; then
+#			return 0
+#		fi
 		if (( current_second_in_day >= daily_start_second && current_second_in_day < daily_end_second )); then
 			return 0
 		fi
@@ -51,36 +73,34 @@ tradingActive() {
 
 
 getQuote() {
-	if [[ ! $1 ]]; then
-		echo "Error: no symbol supplied"
-		return 1
-	fi
+	[[ ! $1 ]] && error "No symbol supplied"
 
-	if [[ ! -f "$OUTPUT_FILE" ]] || ( (( current_second - $(date -r "$OUTPUT_FILE" +%s) >= SLEEP_TIME )) && tradingActive ); then
-		quote=$(curl -s --compressed -A "$USER_AGENT" -L "https://www.google.com/search?q=$1" \
-			| grep -Po '(?<=data-attrid="Company Name">).+' \
-			| grep -Po '.+%\)(?=</span>)' \
-			| sed -r 's/−/-/g' \
-			| tr -dc "[[:graph:][:blank:]]" \
-			| sed -r 's/"tfDdVe">[^<]+<\/span>//g' \
-			| sed -r 's/<[^>]+>|&#?[[:alnum:]]+;/'"$DELIM"'/g' \
-			| sed -r 's/'"$DELIM"' | '"$DELIM"'/'"$DELIM"'/g' | tr -s $DELIM \
-			| cut --complement -f 3,6-14,16 -d "$DELIM"
-		)
-		if [[ $quote ]]; then
-			echo -n "$quote" >"$OUTPUT_FILE"
-		fi
+	if [[ ! "$json_instruments" ]]; then
+		json_instruments=$(query "https://api.robinhood.com/instruments/?symbol=$1")
+		write_needed=1
 	fi
+	[[ ! "$json_instruments" ]] && error "Unable to fetch json_instruments"
+	
+	name=$(jq -r '.results[0].simple_name' <<<"$json_instruments")
+	all_day_tradability=$(jq -r '.results[0].all_day_tradability' <<<"$json_instruments")
 
-	if [[ ! $quote ]]; then
-		quote=$(<"$OUTPUT_FILE")
+	
+	if [[ ! "$json_quotes" ]] || okayToQuery; then
+		json_quotes=$(query "https://api.robinhood.com/marketdata/quotes/$1/")
+		write_needed=1
+	else
+		json_quotes=$(sed -n 2p "$OUTPUT_FILE")
 	fi
+	[[ ! "$json_quotes" ]] && error "Unable to fetch json_quotes"
 
-	IFS=$DELIM read name day_price day_change day_percent quote_time ext_label ext_price ext_change ext_percent <<<"$quote"
+	price=$(jq -r '(.last_extended_hours_trade_price // .last_trade_price)' <<<"$json_quotes")
+	prev_close=$(jq -r '.previous_close' <<<"$json_quotes")
+	price_diff=$(bc -l <<<"$price - $prev_close")
+	percent_diff=$(bc -l <<<"$price_diff / $prev_close * 100")
 }
 
 
-currentPhase() {
+getCurrentPhase() {
 	if [[ $day == [1-5] ]]; then
 		if (( current_second_in_day < daily_start_second || current_second_in_day >= daily_end_second )); then
 			echo 0 # closed
@@ -98,8 +118,7 @@ currentPhase() {
 
 
 timeToNextPhase() {
-	local currentPhase=$(currentPhase)
-	case $currentPhase in
+	case $current_phase in
 		0) # closed
 			if (( current_second_in_day < daily_start_second )) && [[ $day == [1-5] ]]; then
 				next_open_day=today
@@ -123,8 +142,7 @@ timeToNextPhase() {
 
 
 outputCurrentPhase() {
-	local currentPhase=$(currentPhase)
-	case $currentPhase in
+	case $current_phase in
 		0) # closed
 			echo "closed" ;;
 		1) # pre-market
@@ -138,8 +156,7 @@ outputCurrentPhase() {
 
 
 outputNextPhase() {
-	local currentPhase=$(currentPhase)
-	case $currentPhase in
+	case $current_phase in
 		0) # closed
 			echo "trading begins" ;;
 		1) # pre-market
@@ -150,24 +167,68 @@ outputNextPhase() {
 			echo "trading ends" ;;
 	esac
 }
-	
+
 
 output() {
-	local price_string="${ext_price:-$day_price} ${ext_change:-$day_change} ${ext_percent:-$day_percent}"
+	local color="white"
+	local arrow="▶"
+	local sign=" "
+	if (( $(bc -l <<<"$price_diff > 0") )); then
+		color="lightgreen"
+		arrow="▲"
+		sign="+"
+	elif (( $(bc -l <<<"$price_diff < 0") )); then
+		color="red"
+		arrow="▼"
+		sign=""
+	fi
+
 	local status_string="$(outputCurrentPhase); $(outputNextPhase) in $(convertFromSeconds $(timeToNextPhase))"
-	printf "%s   : :   %s   : :   %s\n" "$name" "$price_string" "$status_string"
+
+	local span_params="size='9pt' alpha='85%%'"
+
+	printf "<executor.markup.true>%s <span %s>(%s)</span>" \
+		"$name" "$span_params" "$SYMBOL" 
+	printf "   : :   "
+	printf "$%.2f  <span %s color='%s'>%s%s%.2f (%.2f%%)</span>" \
+		"$price" "$span_params" "$color" "$arrow" "$sign" "$price_diff" "$percent_diff"
+	printf "   : :   "
+	printf "%s\n" \
+		 "$status_string"
+
+
+	if [[ $current_phase != $logged_phase ]]; then
+		write_needed=1
+	fi
+
+
+	if [[ $write_needed -eq 1 ]]; then
+		printf "%s\n%s\n%s" "$json_instruments" "$json_quotes" "$current_phase" >"$OUTPUT_FILE"
+	fi
 }
 
+
+if [[ ! -f "$OUTPUT_FILE" ]]; then
+	>"$OUTPUT_FILE"
+fi
+
+readarray -t lines <"$OUTPUT_FILE"
+json_instruments=${lines[0]}
+json_quotes=${lines[1]}
+logged_phase=${lines[2]}
+unset lines
 
 readarray -td "$DELIM" date_output <<<"$(TZ="America/New_York" date "+%w$DELIM%s$DELIM%_H*60**2+%_M*60+%_S")"
 day=${date_output[0]}
 current_second=${date_output[1]}
 current_second_in_day=$(( ${date_output[2]} ))
+unset date_output
+
 daily_start_second=$(convertToSeconds $START_TIME)
 opening_bell_second=$(convertToSeconds $OPENING_BELL_TIME)
 closing_bell_second=$(convertToSeconds $CLOSING_BELL_TIME)
 daily_end_second=$(convertToSeconds $END_TIME)
 seconds_in_day=$(convertToSeconds 24)
-
+current_phase=$(getCurrentPhase)
 
 getQuote $SYMBOL && output
